[package]
name = "deb-rs2"
version = "2.1.0"
authors = ["trickypr <trickypr@users.noreply.github.com>", "Owen DeBiasio <owen.debiasio@gmail.com>"]
edition = "2024"
license = "MIT"
description = "Extracting and grabbing metadata from .deb files, rebuilt for 2027"

[dependencies]
uuid = { version = "0.8", features = ["v4"] }
glob = "0.3"
debcontrol = "0.1.1"
serde = { version = "1.0", default-features = false, optional = true }
tar = "0.4.46"
ar = "0.9.0"
flate2 = "1.1.10"
xz2 = "0.1.7"
